### ISSUE TITLE
Add `github/gitignore` as a backend?

### ISSUE THREAD

**Issue by pat-s** [ropensci/gitignore#13]
It seems that github/gitignore is way more popular than gitignore.io: https://github.com/github/gitignore

Also this is the main source used in many other editors/languages (e.g. vscode).
Haven't explored the exact differences between these two yet - maybe you did already?

**Comment by PMassicotte** [comment]
I have not. Any real benefit of using GitHub at the moment?

**Comment by PMassicotte** [comment]
I just looked at some and they seem identical. I would not be surprised if gitignore.io uses GitHub.

## GitHub

https://github.com/github/gitignore/blob/master/MetaProgrammingSystem.gitignore

```
workspace.xml
junitvmwatcher*.properties
build.properties

# generated java classes and java source files
#   manually add any custom artifacts that can't be generated from the models
#   http://confluence.jetbrains.com/display/MPSD25/HowTo+--+MPS+and+Git
classes_gen
source_gen
source_gen.caches

# generated test code and test results
test_gen
test_gen.caches
TEST-*.xml
junit*.properties
```
## gitignore.io

https://www.gitignore.io/api/metaprogrammingsystem

```
# Created by https://www.gitignore.io/api/metaprogrammingsystem
# Edit at https://www.gitignore.io/?templates=metaprogrammingsystem

### MetaProgrammingSystem ###
workspace.xml
junitvmwatcher*.properties
build.properties

# generated java classes and java source files
#   manually add any custom artifacts that can't be generated from the models
#   http://confluence.jetbrains.com/display/MPSD25/HowTo+--+MPS+and+Git
classes_gen
source_gen
source_gen.caches

# generated test code and test results
test_gen
test_gen.caches
TEST-*.xml
junit*.properties

# End of https://www.gitignore.io/api/metaprogrammingsystem
```

**Comment by pat-s** [comment]
github/gitignore has `docs/` in the template and gitignore.io not (I added this a few weeks ago).

It seems that the first one is way more popular judging based on the stars of the repo.

Maybe not worth the effort to add a second one if both stay somewhat recent.
Would be interesting to know why gitignore.io even started if there was already github/gitignore (assuming that it started earlier seen on the amount of repo stars - just a guess though).

**Comment by dpprdan** [comment]
gitignore.io is now being redirected to https://www.toptal.com/developers/gitignore. Has this always been the case? At least the "Created/Edit at" links used to be under the gitignore.io domain and are now toptal.com. 

This smells just a tad fishy, IMHO, so maybe this strengthens @pat-s's point?

**Comment by dpprdan** [comment]
> Would be interesting to know why gitignore.io even started if there was already github/gitignore (assuming that it started earlier seen on the amount of repo stars - just a guess though).

@pat-s (and FYI @PMassicotte), I was wondering about this as well and did some more digging. Turns out that https://github.com/toptal/gitignore is [3 years old](https://github.com/toptal/gitignore/commit/57d3706774c6a687f6c7c49bf14813bd788f1f0f) and https://github.com/github/gitignore is [10 years old](https://github.com/github/gitignore/commit/b7cc33a99b02fada900d0e4ba6b7bd38a142f064). (ICYMI there is a link to the first commit on the main page of each repo in the "About" section on the right). The gitignore.io repo was started by gitignore.io's founder Joe Blau because the GitHub repo was (in short) [too slow, too strict and not modular enough](https://blog.joeblau.com/gitignore-io-template-fork). In general, gitignore.io's gitignore repo contains many more gitignore files (~500) than GitHub's.

Now gitignore.io was apparently [acquired by Toptal some time ago and migrated](https://github.com/toptal/gitignore.io/pull/494#issuecomment-644059435) to the new URL at the beginning of June. [Not everybody](https://github.com/toptal/gitignore.io/issues/496) [is happy](https://github.com/toptal/gitignore.io/issues/502). 

As for the two repos: There is some code to have Toptal's gitignore [stay in sync](https://github.com/toptal/gitignore#testing) with GitHub's. There is even a [GitHub Action](https://github.com/toptal/gitignore/blob/ec30d45d1d07355c28a530146c107e0f1c91daf0/.github/workflows/lint.yml#L20) that is supposed to run on every push to the repo. This does [not seem to work](https://github.com/toptal/gitignore/actions) at the moment, however, and the Action never ran successfully since it was set up about a year ago, AFAICT. I've tried a little last night to figure out what the problem is, but haven't figured it out.

If the sync should work again, I see no reason to add GitHub's repo as a backend. Toptal's branding is slightly annoying, but AFAICT adding GitHub's repo would require going through GitHub's main API, which, at least to me, seems not worth the hassle.

**Comment by PMassicotte** [comment]
Thank you for the detailed information. Do we know if there is much difference in terms of supported templates between these two repos?

**Comment by dpprdan** [comment]
It is my understanding so far that the Toptal repo contains the templates from the GitHub repo (at least in principle) plus additional ones.
